Quase final

diff --git a/Cadastro b/Cadastro
--- a/Cadastro
+++ b/Cadastro
@@ -17,7 +17,7 @@ data(){
         if [ -z $DATA ]; then
                 echo "Fala mano!" && data ;
         else
-                echo $DATA | grep -E [0-3]{1}[0-9]{1}[/][0-1]{1}[0-9]{1}[/][0-9]{4}$ && echo -e "Data Válida" && email || echo -e "tente novamente" && data
+                echo $DATA | grep -E [0-3]{1}[0-9]{1}[/][0-1]{1}[0-9]{1}[/][0-9]                                                                                        {4}$ && echo -e "Data Válida" && email || echo -e "tente novamente" && data
         fi
 }
 email(){
@@ -25,7 +25,7 @@ read -p "E o seu e-mail: " EMAIL
         if [ -z $EMAIL ]; then
                 echo "Oxe, coloca aí, não vou te hackear não... ;-) " && email ;
         else
-                echo $EMAIL | grep -E '^([a-zA-Z0-9_-.])+@[0-9a-zA-Z.-]+\.[a-z]{2,3}' && echo -e "OK" && RGs || echo -e "E-mail invalido" && email;
+                echo $EMAIL | grep -E '^([a-zA-Z0-9_-.])+@[0-9a-zA-Z.-]+\.[a-z]{                                                                                        2,3}' && echo -e "OK" && RGs || echo -e "E-mail invalido" && email;
         fi
 }
 RGs(){
@@ -33,7 +33,7 @@ read -p "informe seu RG, modelo:  00.000.000-0  " RG
         if [ -z $RG ]; then
                 echo "RG não declarado" && RGs ;
         else
-                echo $RG | grep -E '^[0-9]{1,2}[.]{1}[0-9]{1,3}[.]{1}[0-9]{1,3}[-]{1}[0-9]{1}$' && echo -e "RG válido" && telefone || echo -e "Invalido" && RGs;
+                echo $RG | grep -E '^[0-9]{1,2}[.]{1}[0-9]{1,3}[.]{1}[0-9]{1,3}[                                                                                        -]{1}[0-9]{1}$' && echo -e "RG válido" && telefone || echo -e "Invalido" && RGs;
         fi
 }
 telefone(){
@@ -41,14 +41,14 @@ echo "Você quer cadatrar Número de Celular ou Fixo?"
 read -p "digite '1' para Fixo e '0' para Celular:  " FIXO
 while read -p "Qual seu DDD? " DDD
 do
-        echo $DDD | grep -E '^[0-9]{1,2}$' && echo -e "DDD Válido" && clear && break || echo " Inválido"
+        echo $DDD | grep -E '^[0-9]{1,2}$' && echo -e "DDD Válido" && clear && b                                                                                        reak || echo " Inválido"
 done
         if(( $FIXO == 1));then
         echo "OK, Digite seu Número: " && read NUME ;
-        echo $NUME | grep -E '^[0-9]{4}[-]{0,1}[0-9]{4}$' && echo -e "Número Validado" && echo \($DDD\)$NUME && cpf || echo -e "Número invalido" && telefone ;
+        echo $NUME | grep -E '^[0-9]{4}[-]{0,1}[0-9]{4}$' && echo -e "Número Val                                                                                        idado" && echo \($DDD\)$NUME && cpf || echo -e "Número invalido" && telefone ;
         else
         echo "OK, Modelo do Número: 00000-0000" && read  NUME1 ;
-        echo $NUME1 | grep -E '^[0-9]{5}[-]{0,1}[0-9]{4}$' && echo -e "Número Válido" && echo \($DDD\)$NUME1 && cpf || echo -e "Invalido" && telefone
+        echo $NUME1 | grep -E '^[0-9]{5}[-]{0,1}[0-9]{4}$' && echo -e "Número Vá                                                                                        lido" && echo \($DDD\)$NUME1 && cpf || echo -e "Invalido" && telefone
         fi
 }
 cpf(){
@@ -56,7 +56,7 @@ read -p "Informe seu CPF: " CPF
         if [ -z $CPF ]; then
                 echo "Nenhum dado informado"  && cpf ;
         else
-                echo $CPF | grep -E '^[0-9]{1,3}[.]{0,1}[0-9]{1,3}[.]{0,1}[0-9]{1,3}[-]{1}[0-9]{2}' && echo -e "CPF Válido" && broadcast || echo -e "CPF inválido" && cpf ;
+                echo $CPF | grep -E '^[0-9]{1,3}[.]{0,1}[0-9]{1,3}[.]{0,1}[0-9]{                                                                                        1,3}[-]{1}[0-9]{2}' && echo -e "CPF Válido" && broadcast || echo -e "CPF inválid                                                                                        o" && cpf ;
         fi
 }
 ip(){
@@ -64,7 +64,7 @@ read -p "IP desejado: " IP
         if [ -z $IP ]; then
                 echo "Nenhum IP digitado" && ip;
         else
-echo $IP | grep -E '^(([01]?([0-9]{2})|(2[0-4][0-9])|(25[0-5])\.){2}( ([01]?([0-9]{2})|(2[0-4][0-9])|(25[0-5]))$' && echo -e "IP Válido" && broadcast || echo -e "IP Inválido" && ip
+echo $IP | grep -E '^(([01]?([0-9]{2})|(2[0-4][0-9])|(25[0-5])\.){2}( ([01]?([0-                                                                                        9]{2})|(2[0-4][0-9])|(25[0-5]))$' && echo -e "IP Válido" && broadcast || echo -e                                                                                         "IP Inválido" && ip
         fi
 }
 broadcast(){
@@ -72,12 +72,18 @@ read -p "Digite o Broadcast desejado " BROAD
         if [ -z $BROAD ]; then
                 echo "Nenhum dado recebido" && Sleep 2 && clear && broadcast ;
         else
-                grep $BROAD /home/vagrant/trabalho/Broadcast.txt  &&    echo -e "Castrato finalizado"  && criar   || \
+                grep $BROAD /home/vagrant/trabalho/Broadcast.txt  && echo -e "Ca                                                                                        strato finalizado"  && criar   || \
                 echo -e "Invalido" && broadcast ;
         fi
 }
 criar(){
-         touch $NOME.txt ;
-         echo $NOME,$DATA,$EMAIL,$RG,\($DDD\)$NUME,$CPF,$BROAD >> $NOME.txt
+read -p "Qual nome Arquivo?" ARQUIVO
+        if [ -z $ARQUIVO ] ;then
+        "Nenhum Nome escrito: " && criar ;
+        else
+        touch $ARQUIVO.txt;
+        echo $NOME,$DATA,$EMAIL,$RG,\($DDD\)$NUME,$CPF,$BROAD >> $ARQUIVO.txt
+        exit
+        fi
 }
 nome
