2.0

diff --git a/Cadastro b/Cadastro
--- a/Cadastro
+++ b/Cadastro
@@ -1,7 +1,8 @@
+
 #!/bin/bash
 clear
-echo "BEM VINDO AO SUPER MOTHER FUCK CADASTRO!!"
-#sleep 2
+echo "BEM VINDO AO SUPER CADASTRO!!"
+sleep 2
 clear
 nome(){
 read -p "Digite seu nome: " NOME
@@ -33,21 +34,30 @@ read -p "informe seu RG, modelo:  00.000.000-0  " RG
         if [ -z $RG ]; then
                 echo "RG não declarado" && RGs ;
         else
-                echo $RG | grep -E '^[0-9]{1,2}[.]{1}[0-9]{1,3}[.]{1}[0-9]{1,3}[-]{1}[0-9]{1}$' && echo -e "RG válido" && telefone || echo -e "Invalido" && RGs ;
+                echo $RG | grep -E '^[0-9]{1,2}[.]{1}[0-9]{1,3}[.]{1}[0-9]{1,3}[-]{1}[0-9]{1}$' && echo -e "RG válido" && telefone || echo -e "Invalido" && RGs;
         fi
 }
 telefone(){
 echo "Você quer cadatrar Número de Celular ou Fixo?"
 read -p "digite '1' para Fixo e '0' para Celular:  " FIXO
+while read -p "Qual seu DDD? " DDD
+do
+        echo $DDD | grep -E '^[0-9]{1,2}$' && echo -e "DDD Válido" && clear && break || echo " Inválido"
+done
         if(( $FIXO == 1));then
-        echo "informe seu DDD: "
-        read DDD ;
-        echo $DDD | grep '^[0-9]{1,2}' &&  echo -e "DDD Válido, pode Prosseguir" || echo -e "Mano tá errado, mas vamos esquecer por enquanto...";
-        echo "OK, Modelo do Número: " && read NUME ;
-        echo $NUME | grep -E '^[0-9]{4}[-]{0,1}[0-9]{4}$' && echo -e "Número Validado" || echo -e "Número invalido";
-        echo \( $DDD \) $NUME ;
+        echo "OK, Digite seu Número: " && read NUME ;
+        echo $NUME | grep -E '^[0-9]{4}[-]{0,1}[0-9]{4}$' && echo -e "Número Validado" && echo \($DDD\)$NUME && cpf || echo -e "Número invalido";
         else
         echo "OK, Modelo do Número: 00000-0000" && read  NUME1 ;
+        echo $NUME1 | grep -E '^[0-9]{5}[-]{0,1}[0-9]{4}$' && echo -e "Número Válido" && echo \($DDD\)$NUME1 && cpf || echo -e "Invalido" && telefone
         fi
-        }
+}
+cpf(){
+read -p "Informe seu CPF: " CPF
+        if [ -z $CPF ]; then
+        echo "Nenhum dado informado"  && cpf ;
+        else
+        echo $CPF | grep -E '^[0-9]{1,3}[.]{0,1}[0-9]{1,3}[.]{0,1}[0-9]{1,3}[-]{1}[0-9]{2}' && echo -e "CPF Válido" && cpf || echo -e "CPF inválido" && cpf ;
+        fi
+}
 nome
